import type { Commands } from '../../shared/ipc'

type Local = 'getAppInfo' | 'pickFolder' | 'openNotificationSettings' | 'simulatorScreenshot' | 'getHostStatus' | 'restartHost' | 'stopHost'

const names: Record<Exclude<keyof Commands, Local>, true> = {
  listAccounts: true,
  addAccount: true,
  removeAccount: true,
  revalidateAccount: true,
  setLinearKey: true,
  clearLinearKey: true,
  hasLinearKey: true,
  getSnapshot: true,
  startChat: true,
  continueOnAccount: true,
  departmentRules: true,
  sendMessage: true,
  interruptChat: true,
  stopTask: true,
  rewindFiles: true,
  stopChat: true,
  setModel: true,
  setEffort: true,
  setPlanMode: true,
  setOpenChat: true,
  olderRows: true,
  getDraft: true,
  saveDraft: true,
  resumeChat: true,
  markRead: true,
  resolveRequest: true,
  listRules: true,
  revokeRule: true,
  recentFolders: true,
  getSettings: true,
  setSetting: true,
  getReview: true,
  getCiLog: true,
  openInEditor: true,
  getHousekeeping: true,
  stopProcesses: true,
  archiveChat: true,
  cleanUp: true,
  removeWorktree: true,
  removeVisitorWorktree: true,
  setThresholds: true,
  finishChat: true,
  finishChats: true,
  getShipIt: true,
  getCommands: true,
  lookupTicket: true,
  moveTicket: true,
  getReviewRequests: true,
  startReview: true,
  installHook: true,
  uninstallHook: true,
  moveIntoOffice: true,
  archiveVisitor: true,
}

export const forwarded = Object.keys(names) as (keyof typeof names)[]
