import { contextBridge, ipcRenderer, webUtils, type IpcRendererEvent } from 'electron'
import type { Events, OfficeApi } from '../shared/ipc'

function subscribe<K extends keyof Events>(name: K, listener: (payload: Events[K]) => void): () => void {
  const handler = (_event: IpcRendererEvent, payload: Events[K]) => listener(payload)
  ipcRenderer.on(name, handler)
  return () => ipcRenderer.off(name, handler)
}

const office: OfficeApi = {
  getAppInfo: () => ipcRenderer.invoke('getAppInfo'),
  listAccounts: () => ipcRenderer.invoke('listAccounts'),
  addAccount: (label, token) => ipcRenderer.invoke('addAccount', label, token),
  removeAccount: (id) => ipcRenderer.invoke('removeAccount', id),
  revalidateAccount: (id) => ipcRenderer.invoke('revalidateAccount', id),
  setLinearKey: (key) => ipcRenderer.invoke('setLinearKey', key),
  clearLinearKey: () => ipcRenderer.invoke('clearLinearKey'),
  hasLinearKey: () => ipcRenderer.invoke('hasLinearKey'),
  setJevKey: (key) => ipcRenderer.invoke('setJevKey', key),
  clearJevKey: () => ipcRenderer.invoke('clearJevKey'),
  hasJevKey: () => ipcRenderer.invoke('hasJevKey'),
  getSnapshot: () => ipcRenderer.invoke('getSnapshot'),
  startChat: (accountId, cwd, prompt, model, effort, options) => ipcRenderer.invoke('startChat', accountId, cwd, prompt, model, effort, options),
  continueOnAccount: (chatId, accountId) => ipcRenderer.invoke('continueOnAccount', chatId, accountId),
  departmentRules: () => ipcRenderer.invoke('departmentRules'),
  sendMessage: (chatId, text, attachments) => ipcRenderer.invoke('sendMessage', chatId, text, attachments),
  pathForFile: (file) => webUtils.getPathForFile(file),
  interruptChat: (chatId) => ipcRenderer.invoke('interruptChat', chatId),
  stopTask: (chatId, id) => ipcRenderer.invoke('stopTask', chatId, id),
  rewindFiles: (chatId, messageId, dryRun) => ipcRenderer.invoke('rewindFiles', chatId, messageId, dryRun),
  stopChat: (chatId) => ipcRenderer.invoke('stopChat', chatId),
  setModel: (chatId, model) => ipcRenderer.invoke('setModel', chatId, model),
  setEffort: (chatId, effort) => ipcRenderer.invoke('setEffort', chatId, effort),
  setPlanMode: (chatId, on) => ipcRenderer.invoke('setPlanMode', chatId, on),
  setOpenChat: (chatId) => ipcRenderer.invoke('setOpenChat', chatId),
  olderRows: (chatId, beforeId) => ipcRenderer.invoke('olderRows', chatId, beforeId),
  getDraft: (chatId) => ipcRenderer.invoke('getDraft', chatId),
  saveDraft: (chatId, text) => ipcRenderer.invoke('saveDraft', chatId, text),
  resumeChat: (chatId) => ipcRenderer.invoke('resumeChat', chatId),
  markRead: (chatId) => ipcRenderer.invoke('markRead', chatId),
  resolveRequest: (requestId, decision, source) => ipcRenderer.invoke('resolveRequest', requestId, decision, source),
  listRules: () => ipcRenderer.invoke('listRules'),
  revokeRule: (id) => ipcRenderer.invoke('revokeRule', id),
  recentFolders: () => ipcRenderer.invoke('recentFolders'),
  pickFolder: () => ipcRenderer.invoke('pickFolder'),
  getSettings: () => ipcRenderer.invoke('getSettings'),
  setSetting: (name, value) => ipcRenderer.invoke('setSetting', name, value),
  openNotificationSettings: () => ipcRenderer.invoke('openNotificationSettings'),
  simulatorScreenshot: (device) => ipcRenderer.invoke('simulatorScreenshot', device),
  openArtifact: (path, url) => ipcRenderer.invoke('openArtifact', path, url),
  getReview: (chatId) => ipcRenderer.invoke('getReview', chatId),
  getCiLog: (chatId, checkId) => ipcRenderer.invoke('getCiLog', chatId, checkId),
  previewFile: (chatId, path) => ipcRenderer.invoke('previewFile', chatId, path),
  openInEditor: (chatId, path, line) => ipcRenderer.invoke('openInEditor', chatId, path, line),
  getHousekeeping: (fresh) => ipcRenderer.invoke('getHousekeeping', fresh),
  stopProcesses: (chatId) => ipcRenderer.invoke('stopProcesses', chatId),
  archiveChat: (chatId) => ipcRenderer.invoke('archiveChat', chatId),
  cleanUp: (chatIds) => ipcRenderer.invoke('cleanUp', chatIds),
  removeWorktree: (path) => ipcRenderer.invoke('removeWorktree', path),
  removeVisitorWorktree: (chatId) => ipcRenderer.invoke('removeVisitorWorktree', chatId),
  setThresholds: (thresholds) => ipcRenderer.invoke('setThresholds', thresholds),
  finishChat: (chatId, removeWorktree) => ipcRenderer.invoke('finishChat', chatId, removeWorktree),
  finishChats: (chatIds, removeWorktrees) => ipcRenderer.invoke('finishChats', chatIds, removeWorktrees),
  getShipIt: (chatId) => ipcRenderer.invoke('getShipIt', chatId),
  getCommands: (target) => ipcRenderer.invoke('getCommands', target),
  lookupTicket: (text) => ipcRenderer.invoke('lookupTicket', text),
  moveTicket: (chatId) => ipcRenderer.invoke('moveTicket', chatId),
  getReviewRequests: () => ipcRenderer.invoke('getReviewRequests'),
  startReview: (url) => ipcRenderer.invoke('startReview', url),
  installHook: () => ipcRenderer.invoke('installHook'),
  uninstallHook: () => ipcRenderer.invoke('uninstallHook'),
  moveIntoOffice: (chatId) => ipcRenderer.invoke('moveIntoOffice', chatId),
  archiveVisitor: (chatId) => ipcRenderer.invoke('archiveVisitor', chatId),
  openInTerminal: (chatId) => ipcRenderer.invoke('openInTerminal', chatId),
  openInDesktop: (chatId) => ipcRenderer.invoke('openInDesktop', chatId),
  getHostStatus: () => ipcRenderer.invoke('getHostStatus'),
  getAppUpdate: () => ipcRenderer.invoke('getAppUpdate'),
  installAppUpdate: () => ipcRenderer.invoke('installAppUpdate'),
  restartHost: () => ipcRenderer.invoke('restartHost'),
  stopHost: () => ipcRenderer.invoke('stopHost'),
  setPaused: (on) => ipcRenderer.invoke('setPaused', on),
  setLimits: (chatId, limits) => ipcRenderer.invoke('setLimits', chatId, limits),
  searchChats: (query) => ipcRenderer.invoke('searchChats', query),
  openTranscript: (sessionId) => ipcRenderer.invoke('openTranscript', sessionId),
  renameChat: (chatId, title) => ipcRenderer.invoke('renameChat', chatId, title),
  onWindowVisibility: (listener) => subscribe('windowVisibility', listener),
  onAccountsChanged: (listener) => subscribe('accountsChanged', listener),
  onChatPatches: (listener) => subscribe('chatPatches', listener),
  onNavigate: (listener) => subscribe('navigate', listener),
  onHousekeeping: (listener) => subscribe('housekeeping', listener),
  onReviewRequests: (listener) => subscribe('reviewRequests', listener),
  onHostStatus: (listener) => subscribe('hostStatus', listener),
  onAppUpdate: (listener) => subscribe('appUpdate', listener),
}

contextBridge.exposeInMainWorld('office', office)
